# Generated by Django 4.0.5 on 2022-06-08 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'socials',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=45)),
                ('contact', models.CharField(max_length=45)),
                ('profile_image', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('social_account_id', models.CharField(max_length=200)),
                ('terms_agreements', models.JSONField()),
                ('social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.social')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
